export const ROLES = [
  'Founder',
  'Software Engineer',
  'Frontend Developer',
  'Backend Developer',
  'Full Stack Developer',
  'Mobile Developer',
  'DevOps Engineer',
  'Data Scientist',
  'Machine Learning Engineer',
  'Product Manager',
  'Product Designer',
  'UX Designer',
  'UI Designer',
  'Hardware Engineer',
  'Mechanical Engineer',
  'Electrical Engineer',
  'Researcher',
  'Marketer',
  'Business Development',
  'Operations',
  'Finance',
  'Legal',
] as const;

export const SKILLS = [
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C++',
  'Rust',
  'Go',
  'Swift',
  'Kotlin',
  'React',
  'Vue',
  'Angular',
  'Node.js',
  'Django',
  'Flask',
  'Rails',
  'Spring',
  'Next.js',
  'GraphQL',
  'REST APIs',
  'SQL',
  'PostgreSQL',
  'MongoDB',
  'Redis',
  'AWS',
  'GCP',
  'Azure',
  'Docker',
  'Kubernetes',
  'CI/CD',
  'Machine Learning',
  'Deep Learning',
  'NLP',
  'Computer Vision',
  'Figma',
  'Adobe XD',
  'Sketch',
  'UI Design',
  'UX Research',
  'Prototyping',
  'Product Strategy',
  'Agile',
  'Scrum',
  'User Research',
  'A/B Testing',
  'Analytics',
  'SEO',
  'Content Marketing',
  'Social Media',
  'Sales',
  'Fundraising',
  'Pitch Decks',
  'Financial Modeling',
  'Legal',
] as const;

export const PROJECT_INTERESTS = [
  'SaaS',
  'B2B',
  'B2C',
  'Marketplace',
  'Fintech',
  'Healthtech',
  'Edtech',
  'Climate Tech',
  'AI/ML',
  'Developer Tools',
  'No-code/Low-code',
  'Hardware',
  'Robotics',
  'Web3/Crypto',
  'E-commerce',
  'Consumer App',
  'Enterprise Software',
  'Mobile App',
  'Open Source',
  'Research Project',
  'Hackathon Project',
  'Side Project',
  'Non-profit',
] as const;

export const PROJECT_TYPES = [
  'Startup (equity only)',
  'Startup (salaried)',
  'Hacakthon team',
  'Side project',
  'Open source',
  'Research collaboration',
  'Consulting project',
  'Freelance project',
] as const;

export const AVAILABILITY_LABELS: Record<string, string> = {
  few_hours: 'Few hrs/week',
  ten_plus_hours: '10+ hrs/week',
  full_time: 'Full-time',
};

export const COMMITMENT_LABELS: Record<string, string> = {
  weekend: 'Weekend warrior',
  few_months: 'Few months',
  long_term: 'Long-term',
  open_ended: 'Open-ended',
};
